# Generated by Django 3.1.7 on 2021-04-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobNo', models.IntegerField()),
                ('jobDate', models.DateField()),
                ('lc', models.CharField(max_length=100)),
                ('lcDate', models.DateField()),
                ('bl', models.CharField(max_length=100)),
                ('blDate', models.DateField()),
                ('igm', models.CharField(max_length=100)),
                ('igmDate', models.DateField()),
                ('index', models.IntegerField()),
                ('vessel', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('containers', models.IntegerField()),
                ('size', models.IntegerField()),
                ('dv', models.FloatField()),
                ('invoiceValue', models.FloatField()),
                ('exchangeRate', models.FloatField()),
                ('valuePKR', models.FloatField()),
                ('insurance', models.FloatField(blank=True, null=True)),
                ('landingCharges', models.FloatField(blank=True, null=True)),
                ('importValue', models.FloatField()),
                ('customDuty', models.FloatField(blank=True, null=True)),
                ('addCustomDuty', models.FloatField(blank=True, null=True)),
                ('salesTax', models.FloatField(blank=True, null=True)),
                ('incomeTax', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('excise', models.FloatField(blank=True, null=True)),
                ('deliveryOrder', models.FloatField(blank=True, null=True)),
                ('terminalWharfage', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
    ]
